### ISSUE TITLE
Add option in configuration to conditionally add the plugin in pages

### ISSUE THREAD

**Issue by oorestisime** [barrymcgee/gatsby-plugin-scroll-indicator#1]
Right now the plugin is activated in all pages

If it could be activated on specific ones pages it could be better. 

Use case activate this only on the blog entries of a blog rather than the index or the archive.

**Comment by juancuiule** [comment]
@barrymcgee are you willing to accept PRs with this kind of feature?
@oorestisime I'm looking for this feature too, but I'm not sure how it should be configured...
- path: only show in paths like `/blog/*`?
- add some kind of key, id, property to layouts that use it?
- something different

**Comment by oorestisime** [comment]
i would assume by path?or maybe list of paths

**Comment by barrymcgee** [comment]
@juancuiule Absolutely I accept PRs. this has been on my to-do but I've bene swamped for the past few weeks.

I had assumed paths was the logical way to approach it - I also assume it would be easier to provide a whitelist of paths rather than a blacklist.

**Comment by juancuiule** [comment]
Nice, I'll take a look at this and see if I can find a way to implement this.

**Comment by shylands** [comment]
+1 for this!

**Comment by barrymcgee** [comment]
I've just cut a new release with this feature and published to NPM - [v0.1.0](https://www.npmjs.com/package/gatsby-plugin-scroll-indicator)

Hope it works as you would expect - please do let me know if you find any bugs. 🙏🏻

**Comment by shylands** [comment]
Awesome cheers @barrymcgee! I've just implemented it here, seems to work a treat :)  https://climatechoice.netlify.com/change-how-you-eat/

**Comment by barrymcgee** [comment]
@shylands Nice! 🙌🏻🌍
