### ISSUE TITLE
Keeps adding the scroll indicator div

### ISSUE THREAD

**Issue by erkro1** [barrymcgee/gatsby-plugin-scroll-indicator#12]
Since the `paths` option was added the plugin keeps adding a scroll indicator div when changing pages, even if one exists already.

**Comment by barrymcgee** [comment]
@erkro1 Thanks for raising - will investigate.

**Comment by barrymcgee** [comment]
@erkro1 Please bump your version of this plugin to `v0.1.1` to resolve this bug.

**Comment by erkro1** [comment]
@barrymcgee Still not working correctly, now it removes the element when navigating if the element already exists. There should be a check [here ](https://github.com/barrymcgee/gatsby-plugin-scroll-indicator/blob/master/src/gatsby-browser.js#L71) to only remove it when the scroller is not enabled.

**Comment by barrymcgee** [comment]
@erkro1 Sorry, just pushed a fix under `v0.1.2` - let me know if that fixes it for you.

**Comment by erkro1** [comment]
@barrymcgee Works great now, thanks!
