### ISSUE TITLE
Scroll indicator hides behind navbar

### ISSUE THREAD

**Issue by php7webmob** [barrymcgee/gatsby-plugin-scroll-indicator#51]
I think it's a z-index issue. How can I manage it by passing some prop?

**Comment by barrymcgee** [comment]
@php7webmob You can't currently but I'll add it as a config option.

**Comment by php7webmob** [comment]
> @php7webmob You can't currently but I'll add it as a config option.

cool.

**Comment by barrymcgee** [comment]
@php7webmob Done, upgrade your dep as follows;

`npm i gatsby-plugin-scroll-indicator@0.1.4`

**Comment by php7webmob** [comment]
> @php7webmob Done, upgrade your dep as follows;
> 
> `npm i gatsby-plugin-scroll-indicator@0.1.4`

Thank you so much! How can I pass z-index prop now?

**Comment by barrymcgee** [comment]
@php7webmob Add it the config - see the example: https://github.com/barrymcgee/gatsby-plugin-scroll-indicator#example
