### ISSUE TITLE
Height and Gradient Color Options

### ISSUE THREAD

**Issue by yudyananda** [barrymcgee/gatsby-plugin-scroll-indicator#82]
Hi @barrymcgee 

Actually this is not an issue but a request or proposal to add height and color gradation options, so i dont have to override things via css. 

I think both of these options can add a plus. hope you consider this proposal

thanks

**Comment by barrymcgee** [comment]
@yudyananda Thanks for this - seems reasonable. I'll try and get this done in the next couple of weeks.

**Comment by barrymcgee** [comment]
@yudyananda These options are now available in the v1.0.0 release.

**Comment by yudyananda** [comment]
awesome! thank you 🙏🏻
